(trace 1 (trace 0 (null)))
(trace 3 (trace 2 (trace 1 (trace 0 (null)))))
(trace 6 (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))))))
(trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))
(trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))))))
(trace 2 (trace 1 (trace 0 (null))))
(trace 100 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))
(trace 0 (null))
(trace
 7
 (trace 6 (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 |#1|))))))))))
  (=
   |#1|
   (trace
    5
    (trace
     10
     (trace
      9
      (trace
       8
       (trace
        7
        (trace
         6
         (trace
          5
          (trace
           10
           (trace
            9
            (trace
             8
             (trace
              7
              (trace
               6
               (trace
                5
                (trace
                 10
                 (trace
                  9
                  (trace
                   8
                   (trace
                    7
                    (trace
                     6
                     (trace
                      5
                      (trace
                       10
                       (trace
                        9
                        (trace
                         8
                         (trace
                          7
                          (trace 6 (trace 5 ...))))))))))))))))))))))))))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 |#1|))))))))))
  (=
   |#1|
   (trace
    8
    (trace
     7
     (trace
      6
      (trace
       5
       (trace
        10
        (trace
         9
         (trace
          8
          (trace
           7
           (trace
            6
            (trace
             5
             (trace
              10
              (trace
               9
               (trace
                8
                (trace
                 7
                 (trace
                  6
                  (trace
                   5
                   (trace
                    10
                    (trace
                     9
                     (trace
                      8
                      (trace
                       7
                       (trace
                        6
                        (trace
                         5
                         (trace
                          10
                          (trace 9 (trace 8 ...))))))))))))))))))))))))))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 4 (trace 3 |#1|))))))))))
  (= |#1| (trace 2 (trace 1 (trace 0 (null)))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      4
                      (trace
                       3
                       (trace
                        2
                        (trace 1 (trace 0 (null)))))))))))))))))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 |#1|))))))))))
  (=
   |#1|
   (trace
    9
    (trace
     8
     (trace
      7
      (trace
       6
       (trace
        5
        (trace
         10
         (trace
          9
          (trace
           8
           (trace
            7
            (trace
             6
             (trace
              5
              (trace
               10
               (trace
                9
                (trace
                 8
                 (trace
                  7
                  (trace
                   6
                   (trace
                    5
                    (trace
                     10
                     (trace
                      9
                      (trace
                       8
                       (trace
                        7
                        (trace
                         6
                         (trace
                          5
                          (trace 10 (trace 9 ...))))))))))))))))))))))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 |#1|))))))))))
  (=
   |#1|
   (trace
    6
    (trace
     5
     (trace
      10
      (trace
       9
       (trace
        8
        (trace
         7
         (trace
          6
          (trace
           5
           (trace
            10
            (trace
             9
             (trace
              8
              (trace
               7
               (trace
                6
                (trace
                 5
                 (trace
                  10
                  (trace
                   9
                   (trace
                    8
                    (trace
                     7
                     (trace
                      6
                      (trace
                       5
                       (trace
                        10
                        (trace
                         9
                         (trace
                          8
                          (trace 7 (trace 6 ...))))))))))))))))))))))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 |#1|))))))))))
  (= |#1| (trace 0 (null)))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 |#1|))))))))))
  (=
   |#1|
   (trace
    7
    (trace
     6
     (trace
      5
      (trace
       10
       (trace
        9
        (trace
         8
         (trace
          7
          (trace
           6
           (trace
            5
            (trace
             10
             (trace
              9
              (trace
               8
               (trace
                7
                (trace
                 6
                 (trace
                  5
                  (trace
                   10
                   (trace
                    9
                    (trace
                     8
                     (trace
                      7
                      (trace
                       6
                       (trace
                        5
                        (trace
                         10
                         (trace
                          9
                          (trace 8 (trace 7 ...))))))))))))))))))))))))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 |#1|))))))))))
  (=
   |#1|
   (trace
    5
    (trace
     10
     (trace
      9
      (trace
       8
       (trace
        7
        (trace
         6
         (trace
          5
          (trace
           10
           (trace
            9
            (trace
             8
             (trace
              7
              (trace
               6
               (trace
                5
                (trace
                 10
                 (trace
                  9
                  (trace
                   8
                   (trace
                    7
                    (trace
                     6
                     (trace
                      5
                      (trace
                       10
                       (trace
                        9
                        (trace
                         8
                         (trace
                          7
                          (trace 6 (trace 5 ...))))))))))))))))))))))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 |#1|))))))))))
  (=
   |#1|
   (trace
    9
    (trace
     8
     (trace
      7
      (trace
       6
       (trace
        5
        (trace
         10
         (trace
          9
          (trace
           8
           (trace
            7
            (trace
             6
             (trace
              5
              (trace
               10
               (trace
                9
                (trace
                 8
                 (trace
                  7
                  (trace
                   6
                   (trace
                    5
                    (trace
                     4
                     (trace
                      3
                      (trace 2 (trace 1 (trace 0 (null))))))))))))))))))))))))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 |#1|))))))))))
  (=
   |#1|
   (trace
    8
    (trace
     7
     (trace
      6
      (trace
       5
       (trace
        10
        (trace
         9
         (trace
          8
          (trace
           7
           (trace
            6
            (trace
             5
             (trace
              10
              (trace
               9
               (trace
                8
                (trace
                 7
                 (trace
                  6
                  (trace
                   5
                   (trace
                    10
                    (trace
                     9
                     (trace
                      8
                      (trace
                       7
                       (trace
                        6
                        (trace
                         5
                         (trace
                          4
                          (trace 3 (trace 2 ...))))))))))))))))))))))))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 |#1|))))))))))
  (=
   |#1|
   (trace
    5
    (trace
     10
     (trace
      9
      (trace
       8
       (trace
        7
        (trace
         6
         (trace
          5
          (trace
           10
           (trace
            9
            (trace
             8
             (trace
              7
              (trace
               6
               (trace
                5
                (trace
                 10
                 (trace
                  9
                  (trace
                   8
                   (trace
                    7
                    (trace
                     6
                     (trace
                      5
                      (trace
                       10
                       (trace
                        9
                        (trace
                         8
                         (trace
                          7
                          (trace 6 (trace 5 ...))))))))))))))))))))))))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 |#1|))))))))))
  (=
   |#1|
   (trace
    5
    (trace
     10
     (trace
      9
      (trace
       8
       (trace
        7
        (trace
         6
         (trace
          5
          (trace
           10
           (trace
            9
            (trace
             8
             (trace
              7
              (trace
               6
               (trace
                5
                (trace
                 10
                 (trace
                  9
                  (trace
                   8
                   (trace
                    7
                    (trace
                     6
                     (trace
                      5
                      (trace
                       4
                       (trace
                        3
                        (trace
                         2
                         (trace 1 (trace 0 (null))))))))))))))))))))))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 |#1|))))))))))
  (=
   |#1|
   (trace
    6
    (trace
     5
     (trace
      10
      (trace
       9
       (trace
        8
        (trace
         7
         (trace
          6
          (trace
           5
           (trace
            10
            (trace
             9
             (trace
              8
              (trace
               7
               (trace
                6
                (trace
                 5
                 (trace
                  10
                  (trace
                   9
                   (trace
                    8
                    (trace
                     7
                     (trace
                      6
                      (trace
                       5
                       (trace
                        10
                        (trace
                         9
                         (trace
                          8
                          (trace 7 (trace 6 ...))))))))))))))))))))))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                4
                (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))))))))))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 |#1|))))))))))
  (=
   |#1|
   (trace
    7
    (trace
     6
     (trace
      5
      (trace
       10
       (trace
        9
        (trace
         8
         (trace
          7
          (trace
           6
           (trace
            5
            (trace
             10
             (trace
              9
              (trace
               8
               (trace
                7
                (trace
                 6
                 (trace
                  5
                  (trace
                   10
                   (trace
                    9
                    (trace
                     8
                     (trace
                      7
                      (trace
                       6
                       (trace
                        5
                        (trace
                         10
                         (trace
                          9
                          (trace 8 (trace 7 ...))))))))))))))))))))))))))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 |#1|))))))))))
  (=
   |#1|
   (trace
    8
    (trace
     7
     (trace
      6
      (trace
       5
       (trace
        10
        (trace
         9
         (trace
          8
          (trace
           7
           (trace
            6
            (trace
             5
             (trace
              10
              (trace
               9
               (trace
                8
                (trace
                 7
                 (trace
                  6
                  (trace
                   5
                   (trace
                    10
                    (trace
                     9
                     (trace
                      8
                      (trace
                       7
                       (trace
                        6
                        (trace
                         5
                         (trace
                          10
                          (trace 9 (trace 8 ...))))))))))))))))))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 |#1|))))))))))
  (=
   |#1|
   (trace
    9
    (trace
     8
     (trace
      7
      (trace
       6
       (trace
        5
        (trace
         10
         (trace
          9
          (trace
           8
           (trace
            7
            (trace
             6
             (trace
              5
              (trace
               10
               (trace
                9
                (trace
                 8
                 (trace
                  7
                  (trace
                   6
                   (trace
                    5
                    (trace
                     10
                     (trace
                      9
                      (trace
                       8
                       (trace
                        7
                        (trace
                         6
                         (trace
                          5
                          (trace 4 (trace 3 ...))))))))))))))))))))))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 4 ...))))))))))))))))))))))))))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 |#1|))))))))))
  (=
   |#1|
   (trace
    8
    (trace
     7
     (trace
      6
      (trace
       5
       (trace
        10
        (trace
         9
         (trace
          8
          (trace
           7
           (trace
            6
            (trace
             5
             (trace
              4
              (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))))))))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 |#1|))))))))))
  (=
   |#1|
   (trace
    6
    (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 |#1|))))))))))
  (= |#1| (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 |#1|))))))))))
  (=
   |#1|
   (trace
    6
    (trace
     5
     (trace
      10
      (trace
       9
       (trace
        8
        (trace
         7
         (trace
          6
          (trace
           5
           (trace
            10
            (trace
             9
             (trace
              8
              (trace
               7
               (trace
                6
                (trace
                 5
                 (trace
                  10
                  (trace
                   9
                   (trace
                    8
                    (trace
                     7
                     (trace
                      6
                      (trace
                       5
                       (trace
                        10
                        (trace
                         9
                         (trace
                          8
                          (trace 7 (trace 6 ...))))))))))))))))))))))))))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 |#1|))))))))))
  (=
   |#1|
   (trace
    7
    (trace
     6
     (trace
      5
      (trace
       10
       (trace
        9
        (trace
         8
         (trace
          7
          (trace
           6
           (trace
            5
            (trace
             10
             (trace
              9
              (trace
               8
               (trace
                7
                (trace
                 6
                 (trace
                  5
                  (trace
                   10
                   (trace
                    9
                    (trace
                     8
                     (trace
                      7
                      (trace
                       6
                       (trace
                        5
                        (trace
                         10
                         (trace
                          9
                          (trace 8 (trace 7 ...))))))))))))))))))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 |#1|))))))))))
  (=
   |#1|
   (trace
    9
    (trace
     8
     (trace
      7
      (trace
       6
       (trace
        5
        (trace
         10
         (trace
          9
          (trace
           8
           (trace
            7
            (trace
             6
             (trace
              5
              (trace
               10
               (trace
                9
                (trace
                 8
                 (trace
                  7
                  (trace
                   6
                   (trace
                    5
                    (trace
                     10
                     (trace
                      9
                      (trace
                       8
                       (trace
                        7
                        (trace
                         6
                         (trace
                          5
                          (trace 10 (trace 9 ...))))))))))))))))))))))))))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 |#1|))))))))))
  (=
   |#1|
   (trace
    7
    (trace
     6
     (trace
      5
      (trace
       10
       (trace
        9
        (trace
         8
         (trace
          7
          (trace
           6
           (trace
            5
            (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))))))))))))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 |#1|))))))))))
  (=
   |#1|
   (trace
    7
    (trace
     6
     (trace
      5
      (trace
       10
       (trace
        9
        (trace
         8
         (trace
          7
          (trace
           6
           (trace
            5
            (trace
             10
             (trace
              9
              (trace
               8
               (trace
                7
                (trace
                 6
                 (trace
                  5
                  (trace
                   4
                   (trace
                    3
                    (trace 2 (trace 1 (trace 0 (null))))))))))))))))))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      4
                      (trace
                       3
                       (trace
                        2
                        (trace 1 (trace 0 (null)))))))))))))))))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 |#1|))))))))))
  (=
   |#1|
   (trace
    9
    (trace
     8
     (trace
      7
      (trace
       6
       (trace
        5
        (trace
         10
         (trace
          9
          (trace
           8
           (trace
            7
            (trace
             6
             (trace
              5
              (trace
               10
               (trace
                9
                (trace
                 8
                 (trace
                  7
                  (trace
                   6
                   (trace
                    5
                    (trace
                     10
                     (trace
                      9
                      (trace
                       8
                       (trace
                        7
                        (trace
                         6
                         (trace
                          5
                          (trace 10 (trace 9 ...))))))))))))))))))))))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 |#1|))))))))))
  (=
   |#1|
   (trace
    6
    (trace
     5
     (trace
      10
      (trace
       9
       (trace
        8
        (trace
         7
         (trace
          6
          (trace
           5
           (trace
            10
            (trace
             9
             (trace
              8
              (trace
               7
               (trace
                6
                (trace
                 5
                 (trace
                  10
                  (trace
                   9
                   (trace
                    8
                    (trace
                     7
                     (trace
                      6
                      (trace
                       5
                       (trace
                        10
                        (trace
                         9
                         (trace
                          8
                          (trace 7 (trace 6 ...))))))))))))))))))))))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 4 ...))))))))))))))))))))))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (= |#1| (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 |#1|))))))))))
  (=
   |#1|
   (trace
    7
    (trace
     6
     (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 4 |#1|))))))))))
  (= |#1| (trace 3 (trace 2 (trace 1 (trace 0 (null))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 |#1|))))))))))
  (=
   |#1|
   (trace
    6
    (trace
     5
     (trace
      10
      (trace
       9
       (trace
        8
        (trace
         7
         (trace
          6
          (trace
           5
           (trace
            10
            (trace
             9
             (trace
              8
              (trace
               7
               (trace
                6
                (trace
                 5
                 (trace
                  10
                  (trace
                   9
                   (trace
                    8
                    (trace
                     7
                     (trace
                      6
                      (trace
                       5
                       (trace
                        4
                        (trace
                         3
                         (trace
                          2
                          (trace 1 (trace 0 ...))))))))))))))))))))))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 |#1|))))))))))
  (=
   |#1|
   (trace
    6
    (trace
     5
     (trace
      10
      (trace
       9
       (trace
        8
        (trace
         7
         (trace
          6
          (trace
           5
           (trace
            10
            (trace
             9
             (trace
              8
              (trace
               7
               (trace
                6
                (trace
                 5
                 (trace
                  10
                  (trace
                   9
                   (trace
                    8
                    (trace
                     7
                     (trace
                      6
                      (trace
                       5
                       (trace
                        10
                        (trace
                         9
                         (trace
                          8
                          (trace 7 (trace 6 ...))))))))))))))))))))))))))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 |#1|))))))))))
  (=
   |#1|
   (trace
    8
    (trace
     7
     (trace
      6
      (trace
       5
       (trace
        10
        (trace
         9
         (trace
          8
          (trace
           7
           (trace
            6
            (trace
             5
             (trace
              10
              (trace
               9
               (trace
                8
                (trace
                 7
                 (trace
                  6
                  (trace
                   5
                   (trace
                    10
                    (trace
                     9
                     (trace
                      8
                      (trace
                       7
                       (trace
                        6
                        (trace
                         5
                         (trace
                          10
                          (trace 9 (trace 8 ...))))))))))))))))))))))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 |#1|))))))))))
  (=
   |#1|
   (trace
    5
    (trace
     10
     (trace
      9
      (trace
       8
       (trace
        7
        (trace
         6
         (trace
          5
          (trace
           10
           (trace
            9
            (trace
             8
             (trace
              7
              (trace
               6
               (trace
                5
                (trace
                 4
                 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))))))))))))))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 |#1|))))))))))
  (= |#1| (null))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 |#1|))))))))))
  (=
   |#1|
   (trace
    8
    (trace
     7
     (trace
      6
      (trace
       5
       (trace
        10
        (trace
         9
         (trace
          8
          (trace
           7
           (trace
            6
            (trace
             5
             (trace
              10
              (trace
               9
               (trace
                8
                (trace
                 7
                 (trace
                  6
                  (trace
                   5
                   (trace
                    4
                    (trace
                     3
                     (trace 2 (trace 1 (trace 0 (null)))))))))))))))))))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 |#1|))))))))))
  (=
   |#1|
   (trace
    9
    (trace
     8
     (trace
      7
      (trace
       6
       (trace
        5
        (trace
         10
         (trace
          9
          (trace
           8
           (trace
            7
            (trace
             6
             (trace
              5
              (trace
               10
               (trace
                9
                (trace
                 8
                 (trace
                  7
                  (trace
                   6
                   (trace
                    5
                    (trace
                     10
                     (trace
                      9
                      (trace
                       8
                       (trace
                        7
                        (trace
                         6
                         (trace
                          5
                          (trace 10 (trace 9 ...))))))))))))))))))))))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 |#1|))))))))))
  (=
   |#1|
   (trace
    6
    (trace
     5
     (trace
      10
      (trace
       9
       (trace
        8
        (trace
         7
         (trace
          6
          (trace
           5
           (trace
            10
            (trace
             9
             (trace
              8
              (trace
               7
               (trace
                6
                (trace
                 5
                 (trace
                  4
                  (trace
                   3
                   (trace 2 (trace 1 (trace 0 (null)))))))))))))))))))))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 4 (trace 3 (trace 2 |#1|))))))))))
  (= |#1| (trace 1 (trace 0 (null))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 |#1|))))))))))
  (=
   |#1|
   (trace
    5
    (trace
     10
     (trace
      9
      (trace
       8
       (trace
        7
        (trace
         6
         (trace
          5
          (trace
           10
           (trace
            9
            (trace
             8
             (trace
              7
              (trace
               6
               (trace
                5
                (trace
                 10
                 (trace
                  9
                  (trace
                   8
                   (trace
                    7
                    (trace
                     6
                     (trace
                      5
                      (trace
                       10
                       (trace
                        9
                        (trace
                         8
                         (trace
                          7
                          (trace 6 (trace 5 ...))))))))))))))))))))))))))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 |#1|))))))))))
  (=
   |#1|
   (trace
    8
    (trace
     7
     (trace
      6
      (trace
       5
       (trace
        10
        (trace
         9
         (trace
          8
          (trace
           7
           (trace
            6
            (trace
             5
             (trace
              10
              (trace
               9
               (trace
                8
                (trace
                 7
                 (trace
                  6
                  (trace
                   5
                   (trace
                    10
                    (trace
                     9
                     (trace
                      8
                      (trace
                       7
                       (trace
                        6
                        (trace
                         5
                         (trace
                          10
                          (trace 9 (trace 8 ...))))))))))))))))))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 |#1|))))))))))
  (=
   |#1|
   (trace
    9
    (trace
     8
     (trace
      7
      (trace
       6
       (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))))))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 |#1|))))))))))
  (=
   |#1|
   (trace
    5
    (trace
     10
     (trace
      9
      (trace
       8
       (trace
        7
        (trace
         6
         (trace
          5
          (trace
           10
           (trace
            9
            (trace
             8
             (trace
              7
              (trace
               6
               (trace
                5
                (trace
                 10
                 (trace
                  9
                  (trace
                   8
                   (trace
                    7
                    (trace
                     6
                     (trace
                      5
                      (trace
                       10
                       (trace
                        9
                        (trace
                         8
                         (trace
                          7
                          (trace 6 (trace 5 ...))))))))))))))))))))))))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 |#1|))))))))))
  (=
   |#1|
   (trace
    5
    (trace
     10
     (trace
      9
      (trace
       8
       (trace
        7
        (trace
         6
         (trace
          5
          (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null))))))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 |#1|))))))))))
  (=
   |#1|
   (trace
    9
    (trace
     8
     (trace
      7
      (trace
       6
       (trace
        5
        (trace
         10
         (trace
          9
          (trace
           8
           (trace
            7
            (trace
             6
             (trace
              5
              (trace
               10
               (trace
                9
                (trace
                 8
                 (trace
                  7
                  (trace
                   6
                   (trace
                    5
                    (trace
                     10
                     (trace
                      9
                      (trace
                       8
                       (trace
                        7
                        (trace
                         6
                         (trace
                          5
                          (trace 10 (trace 9 ...))))))))))))))))))))))))))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 |#1|))))))))))
  (=
   |#1|
   (trace
    7
    (trace
     6
     (trace
      5
      (trace
       10
       (trace
        9
        (trace
         8
         (trace
          7
          (trace
           6
           (trace
            5
            (trace
             10
             (trace
              9
              (trace
               8
               (trace
                7
                (trace
                 6
                 (trace
                  5
                  (trace
                   10
                   (trace
                    9
                    (trace
                     8
                     (trace
                      7
                      (trace
                       6
                       (trace
                        5
                        (trace
                         10
                         (trace
                          9
                          (trace 8 (trace 7 ...))))))))))))))))))))))))))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 |#1|))))))))))
  (=
   |#1|
   (trace
    7
    (trace
     6
     (trace
      5
      (trace
       10
       (trace
        9
        (trace
         8
         (trace
          7
          (trace
           6
           (trace
            5
            (trace
             10
             (trace
              9
              (trace
               8
               (trace
                7
                (trace
                 6
                 (trace
                  5
                  (trace
                   10
                   (trace
                    9
                    (trace
                     8
                     (trace
                      7
                      (trace
                       6
                       (trace
                        5
                        (trace
                         10
                         (trace
                          9
                          (trace 8 (trace 7 ...))))))))))))))))))))))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 |#1|))))))))))
  (=
   |#1|
   (trace
    6
    (trace
     5
     (trace
      10
      (trace
       9
       (trace
        8
        (trace
         7
         (trace
          6
          (trace
           5
           (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 |#1|))))))))))
  (=
   |#1|
   (trace
    9
    (trace
     8
     (trace
      7
      (trace
       6
       (trace
        5
        (trace
         10
         (trace
          9
          (trace
           8
           (trace
            7
            (trace
             6
             (trace
              5
              (trace
               4
               (trace 3 (trace 2 (trace 1 (trace 0 (null))))))))))))))))))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 |#1|))))))))))
  (=
   |#1|
   (trace
    7
    (trace
     6
     (trace
      5
      (trace
       10
       (trace
        9
        (trace
         8
         (trace
          7
          (trace
           6
           (trace
            5
            (trace
             10
             (trace
              9
              (trace
               8
               (trace
                7
                (trace
                 6
                 (trace
                  5
                  (trace
                   10
                   (trace
                    9
                    (trace
                     8
                     (trace
                      7
                      (trace
                       6
                       (trace
                        5
                        (trace
                         4
                         (trace
                          3
                          (trace 2 (trace 1 ...))))))))))))))))))))))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (= |#1| (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))))))))
(trace
 8
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                4
                (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))))))))))))))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 |#1|))))))))))
  (=
   |#1|
   (trace
    8
    (trace
     7
     (trace
      6
      (trace 5 (trace 4 (trace 3 (trace 2 (trace 1 (trace 0 (null)))))))))))
(trace
 5
 (trace
  10
  (trace
   9
   (trace
    8
    (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 |#1|))))))))))
  (=
   |#1|
   (trace
    7
    (trace
     6
     (trace
      5
      (trace
       10
       (trace
        9
        (trace
         8
         (trace
          7
          (trace
           6
           (trace
            5
            (trace
             10
             (trace
              9
              (trace
               8
               (trace
                7
                (trace
                 6
                 (trace
                  5
                  (trace
                   10
                   (trace
                    9
                    (trace
                     8
                     (trace
                      7
                      (trace
                       6
                       (trace
                        5
                        (trace
                         10
                         (trace
                          9
                          (trace 8 (trace 7 ...))))))))))))))))))))))))))
(trace
 10
 (trace
  9
  (trace
   8
   (trace
    7
    (trace 6 (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 |#1|))))))))))
  (=
   |#1|
   (trace
    6
    (trace
     5
     (trace
      10
      (trace
       9
       (trace
        8
        (trace
         7
         (trace
          6
          (trace
           5
           (trace
            10
            (trace
             9
             (trace
              8
              (trace
               7
               (trace
                6
                (trace
                 5
                 (trace
                  10
                  (trace
                   9
                   (trace
                    8
                    (trace
                     7
                     (trace
                      6
                      (trace
                       5
                       (trace
                        10
                        (trace
                         9
                         (trace
                          8
                          (trace 7 (trace 6 ...))))))))))))))))))))))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 7
 (trace
  6
  (trace
   5
   (trace
    10
    (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 |#1|))))))))))
  (=
   |#1|
   (trace
    9
    (trace
     8
     (trace
      7
      (trace
       6
       (trace
        5
        (trace
         10
         (trace
          9
          (trace
           8
           (trace
            7
            (trace
             6
             (trace
              5
              (trace
               10
               (trace
                9
                (trace
                 8
                 (trace
                  7
                  (trace
                   6
                   (trace
                    5
                    (trace
                     10
                     (trace
                      9
                      (trace
                       8
                       (trace
                        7
                        (trace
                         6
                         (trace
                          5
                          (trace 10 (trace 9 ...))))))))))))))))))))))))))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 |#1|))))))))))
  (=
   |#1|
   (trace
    8
    (trace
     7
     (trace
      6
      (trace
       5
       (trace
        10
        (trace
         9
         (trace
          8
          (trace
           7
           (trace
            6
            (trace
             5
             (trace
              10
              (trace
               9
               (trace
                8
                (trace
                 7
                 (trace
                  6
                  (trace
                   5
                   (trace
                    10
                    (trace
                     9
                     (trace
                      8
                      (trace
                       7
                       (trace
                        6
                        (trace
                         5
                         (trace
                          10
                          (trace 9 (trace 8 ...))))))))))))))))))))))))))
(trace
 6
 (trace
  5
  (trace
   10
   (trace
    9
    (trace 8 (trace 7 (trace 6 (trace 5 (trace 10 (trace 9 |#1|))))))))))
  (=
   |#1|
   (trace
    8
    (trace
     7
     (trace
      6
      (trace
       5
       (trace
        10
        (trace
         9
         (trace
          8
          (trace
           7
           (trace
            6
            (trace
             5
             (trace
              10
              (trace
               9
               (trace
                8
                (trace
                 7
                 (trace
                  6
                  (trace
                   5
                   (trace
                    10
                    (trace
                     9
                     (trace
                      8
                      (trace
                       7
                       (trace
                        6
                        (trace
                         5
                         (trace
                          10
                          (trace 9 (trace 8 ...))))))))))))))))))))))))))
(trace
 100
 (trace
  7
  (trace
   6
   (trace
    5
    (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 (trace 5 |#1|))))))))))
  (=
   |#1|
   (trace
    10
    (trace
     9
     (trace
      8
      (trace
       7
       (trace
        6
        (trace
         5
         (trace
          10
          (trace
           9
           (trace
            8
            (trace
             7
             (trace
              6
              (trace
               5
               (trace
                10
                (trace
                 9
                 (trace
                  8
                  (trace
                   7
                   (trace
                    6
                    (trace
                     5
                     (trace
                      10
                      (trace
                       9
                       (trace
                        8
                        (trace
                         7
                         (trace
                          6
                          (trace 5 (trace 10 ...))))))))))))))))))))))))))
(trace
 9
 (trace
  8
  (trace
   7
   (trace
    6
    (trace 5 (trace 10 (trace 9 (trace 8 (trace 7 (trace 6 |#1|))))))))))
  (=
   |#1|
   (trace
    5
    (trace
     10
     (trace
      9
      (trace
       8
       (trace
        7
        (trace
         6
         (trace
          5
          (trace
           10
           (trace
            9
            (trace
             8
             (trace
              7
              (trace
               6
               (trace
                5
                (trace
                 10
                 (trace
                  9
                  (trace
                   8
                   (trace
                    7
                    (trace
                     6
                     (trace
                      5
                      (trace
                       10
                       (trace
                        9
                        (trace
                         8
                         (trace
                          7
                          (trace 6 (trace 5 ...))))))))))))))))))))))))))

(source 5 (i-cmp "iub" (ref "i") (lit 10)))
(source 1 (i-cmp "x0" (ref "x") (lit 0)))
(source 10 (br 5))
(source 8 (i-add "i+1" (ref "i") (lit 1)))
(source 4 (mov "i" (ref "x")))
(source 2 (i-cmp "x<0" (ref "x0") (lit -1)))
(source 9 (mov "i" (ref "i+1")))
(source 0 (mov "x" (sym)))
(source 6 (i-cmp "iub2" (ref "iub") (lit 1)))
(source 3 (brz "x<0" 100))
(source 7 (brz "iub2" 100))
