
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ID LPAREN RPAREN STRINGstatement : IDstatement : ID IDstatement : ID STRINGstatement : ID STRING IDstatement : ID ID STRING'
    
_lr_action_items = {'ID':([0,2,4,],[2,3,6,]),'$end':([1,2,3,4,5,6,],[0,-1,-2,-3,-5,-4,]),'STRING':([2,3,],[4,5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> ID','statement',1,'p_statement_unary','parser.py',50),
  ('statement -> ID ID','statement',2,'p_statement_id_cmd','parser.py',62),
  ('statement -> ID STRING','statement',2,'p_statement_str_cmd','parser.py',70),
  ('statement -> ID STRING ID','statement',3,'p_statement_str_id_cmd','parser.py',84),
  ('statement -> ID ID STRING','statement',3,'p_statement_id_str_cmd','parser.py',89),
]
