
.decl edge(from: number, to: number, weight: number)
.printsize edge
.input edge(filename="c-edge.facts")

.decl node(n: number)
.printsize node
.output node
node(n) :- edge(n, _, _).

.decl degree(n: number, c: number)
.printsize degree
.output degree
degree(n, c) :- node(n), c = count : {edge(n, _, _)}.

.decl node_count(n: number)
.printsize node_count
.output node_count
node_count(s) :- s = count : {node(_)}.
